In [10]:
from sklearn.datasets import load_iris



import pandas as pd
from sklearn.datasets import load_iris

# Cargar el conjunto de datos iris
iris = load_iris()
X = iris.data
y = iris.target

# Convertir a DataFrame de pandas y asignar nombres de columnas
column_names = ['feature1', 'feature2', 'feature3', 'feature4']
df = pd.DataFrame(X, columns=column_names)

# Agregar la columna objetivo al DataFrame
df['producto'] = y

In [11]:
df['id_usuario'] = range(df.shape[0])

In [13]:
df.to_csv('raw_data/feature_data.csv', index=False)

In [3]:
import pandas as pd

df_address = pd.read_csv('clean_data/raw_address_sample.csv')

df_features = pd.read_csv('raw_data/feature_data.csv')

In [1]:
import os
os.path.dirname('./')

'.'

In [6]:
df_features = df_features.set_index('id_usuario').join(df_address.set_index('id_usuario'))

,feature1,feature2,feature3,feature4,producto,direccion
id_usuario,,,,,,
0,5.1,3.5,1.4,0.2,0,CL. 80 # 62 - 54
1,4.9,3.0,1.4,0.2,0,CL. 125 # 40 - 82
2,4.7,3.2,1.3,0.2,0,CRA. 108 # 22 - 62
3,4.6,3.1,1.5,0.2,0,CL. 52 # 24 - 35
4,5.0,3.6,1.4,0.2,0,CRA. 10 # 12 - 53
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,CL. 109 # 67 - 52
146,6.3,2.5,5.0,1.9,2,CL. 108 A # 77 - 16
147,6.5,3.0,5.2,2.0,2,CL. 49 # 93 - 108
148,6.2,3.4,5.4,2.3,2,CRA. 74 # 94 - 124
149,5.9,3.0,5.1,1.8,2,CL. 42 B # 63 - 162